# 220211

# Library

In [1]:
import numpy as np, os
import pandas as pd
import tensorflow as tf
from tqdm import tqdm

# 결과 확인을 용이하게 하기 위한 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# Data load

In [2]:
all_best = pd.read_csv('./dsml_data/df_all_best_for_meth1.csv')
all_diff = pd.read_csv('./dsml_data/df_all_diff_for_meth1.csv')
all_preds = pd.read_csv('./dsml_data/df_all_preds_for_meth1.csv')

d1d5_best = pd.read_csv('./dsml_data/df_d1d5_best_for_meth1.csv')
d1d5_diff = pd.read_csv('./dsml_data/df_d1d5_diff_for_meth1.csv')
d1d5_preds = pd.read_csv('./dsml_data/df_d1d5_preds_for_meth1.csv')

d6d10_best = pd.read_csv('./dsml_data/df_d6d10_best_for_meth1.csv')
d6d10_diff = pd.read_csv('./dsml_data/df_d6d10_diff_for_meth1.csv')
d6d10_preds = pd.read_csv('./dsml_data/df_d6d10_preds_for_meth1.csv')

In [3]:
all_best
all_diff
all_preds

# d1d5_best
# d1d5_diff
# d1d5_preds

# d6d10_best
# d6d10_diff
# d6d10_preds

,feature,baseline_bce,bce,preds_mean,preds2_mean,diff,diff_preds
0,904224461,1.013844,1.011739,0.633561,0.622529,-0.002106,-0.011032
1,69152068,1.013844,1.012304,0.633561,0.633442,-0.001540,-0.000120
2,536242558,1.013844,1.012476,0.633561,0.639803,-0.001368,0.006242
3,91464024,1.013844,1.012594,0.633561,0.640399,-0.001250,0.006838
4,37205036174,1.013844,1.012601,0.633561,0.639982,-0.001243,0.006421
...,...,...,...,...,...,...,...
4063,10019055302,1.013844,1.041340,0.633561,0.766674,0.027495,0.133112
4064,54817525,1.013844,1.042170,0.633561,0.767467,0.028326,0.133906
4065,67434504,1.013844,1.046685,0.633561,0.777882,0.032840,0.144320
4066,74606211,1.013844,1.050331,0.633561,0.784815,0.036486,0.151254
4067,409606211,1.013844,1.073784,0.633561,0.826544,0.059940,0.192982

          feature      diff
0       904224461 -0.002106
1        69152068 -0.001540
2       536242558 -0.001368
3        91464024 -0.001250
4     37205036174 -0.001243
...           ...       ...
4063  10019055302  0.027495
4064     54817525  0.028326
4065     67434504  0.032840
4066     74606211  0.036486
4067    409606211  0.059940

[4068 rows x 2 columns]

          feature  diff_preds
0          227194   -0.136509
1         4003822   -0.122565
2           50889   -0.115312
3     63323016101   -0.114032
4           51200   -0.114011
...           ...         ...
4063  10019055302    0.133112
4064     54817525    0.133906
4065     67434504    0.144320
4066     74606211    0.151254
4067    409606211    0.192982

[4068 rows x 2 columns]

# ~~preds 생성 당시 계산 실수, 부호 전환.~~ 
# 계산 잘 했었음.

In [4]:
#all_preds['diff_preds'] = -all_preds['diff_preds']
#all_preds
#all_preds = all_preds.sort_values('diff_preds', ascending = True)
#all_preds = all_preds.reset_index(drop = True)

In [5]:
#all_preds

In [6]:
#all_best['diff_preds'] = -all_best['diff_preds']
#all_best
#all_best = all_best.sort_values('diff_preds', ascending = True)
#all_best = all_best.reset_index(drop = True)

# ReLU

In [7]:
for i,j in enumerate(all_best['diff']):
    if j <= 0:
        all_best['diff'][i] = 0
all_best

<ipython-input-7-e5297c69b957>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_best['diff'][i] = 0

,feature,baseline_bce,bce,preds_mean,preds2_mean,diff,diff_preds
0,904224461,1.013844,1.011739,0.633561,0.622529,0.000000,-0.011032
1,69152068,1.013844,1.012304,0.633561,0.633442,0.000000,-0.000120
2,536242558,1.013844,1.012476,0.633561,0.639803,0.000000,0.006242
3,91464024,1.013844,1.012594,0.633561,0.640399,0.000000,0.006838
4,37205036174,1.013844,1.012601,0.633561,0.639982,0.000000,0.006421
...,...,...,...,...,...,...,...
4063,10019055302,1.013844,1.041340,0.633561,0.766674,0.027495,0.133112
4064,54817525,1.013844,1.042170,0.633561,0.767467,0.028326,0.133906
4065,67434504,1.013844,1.046685,0.633561,0.777882,0.032840,0.144320
4066,74606211,1.013844,1.050331,0.633561,0.784815,0.036486,0.151254
4067,409606211,1.013844,1.073784,0.633561,0.826544,0.059940,0.192982

In [8]:
for i,j in enumerate(all_diff['diff']):
    if j <= 0:
        all_diff['diff'][i] = 0
all_diff

<ipython-input-8-6ee56b16b301>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_diff['diff'][i] = 0

          feature      diff
0       904224461  0.000000
1        69152068  0.000000
2       536242558  0.000000
3        91464024  0.000000
4     37205036174  0.000000
...           ...       ...
4063  10019055302  0.027495
4064     54817525  0.028326
4065     67434504  0.032840
4066     74606211  0.036486
4067    409606211  0.059940

[4068 rows x 2 columns]

# sign

In [9]:
for i,j in enumerate(all_preds['diff_preds']):
    if j>0:
        all_preds['diff_preds'][i] = 1
#    elif j==0:
#        all_preds['diff_preds'][i] = 0
    elif j<0:
        all_preds['diff_preds'][i] = -1

<ipython-input-9-29953b917f0c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_preds['diff_preds'][i] = -1
<ipython-input-9-29953b917f0c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_preds['diff_preds'][i] = 1

In [10]:
all_preds

          feature  diff_preds
0          227194        -1.0
1         4003822        -1.0
2           50889        -1.0
3     63323016101        -1.0
4           51200        -1.0
...           ...         ...
4063  10019055302         1.0
4064     54817525         1.0
4065     67434504         1.0
4066     74606211         1.0
4067    409606211         1.0

[4068 rows x 2 columns]

In [11]:
for i,j in enumerate(all_best['diff_preds']):
    if j>0:
        all_best['diff_preds'][i] = 1
    elif j==0:
        all_best['diff_preds'][i] = 0
    elif j<0:
        all_best['diff_preds'][i] = -1

<ipython-input-11-62a8ef79243b>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_best['diff_preds'][i] = -1
<ipython-input-11-62a8ef79243b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_best['diff_preds'][i] = 1

# Method1
```
Method1 = diff * diff_preds
Method1 순서대로 (내림차순) sorting
```

In [12]:
all_best['Method1'] = all_best['diff']*all_best['diff_preds']
all_best

,feature,baseline_bce,bce,preds_mean,preds2_mean,diff,diff_preds,Method1
0,904224461,1.013844,1.011739,0.633561,0.622529,0.000000,-1.0,-0.000000
1,69152068,1.013844,1.012304,0.633561,0.633442,0.000000,-1.0,-0.000000
2,536242558,1.013844,1.012476,0.633561,0.639803,0.000000,1.0,0.000000
3,91464024,1.013844,1.012594,0.633561,0.640399,0.000000,1.0,0.000000
4,37205036174,1.013844,1.012601,0.633561,0.639982,0.000000,1.0,0.000000
...,...,...,...,...,...,...,...,...
4063,10019055302,1.013844,1.041340,0.633561,0.766674,0.027495,1.0,0.027495
4064,54817525,1.013844,1.042170,0.633561,0.767467,0.028326,1.0,0.028326
4065,67434504,1.013844,1.046685,0.633561,0.777882,0.032840,1.0,0.032840
4066,74606211,1.013844,1.050331,0.633561,0.784815,0.036486,1.0,0.036486
4067,409606211,1.013844,1.073784,0.633561,0.826544,0.059940,1.0,0.059940

In [13]:
all_best = all_best.sort_values("Method1", ascending= False)

In [14]:
all_best

,feature,baseline_bce,bce,preds_mean,preds2_mean,diff,diff_preds,Method1
4067,409606211,1.013844,1.073784,0.633561,0.826544,0.059940,1.0,0.059940
4066,74606211,1.013844,1.050331,0.633561,0.784815,0.036486,1.0,0.036486
4065,67434504,1.013844,1.046685,0.633561,0.777882,0.032840,1.0,0.032840
4064,54817525,1.013844,1.042170,0.633561,0.767467,0.028326,1.0,0.028326
4063,10019055302,1.013844,1.041340,0.633561,0.766674,0.027495,1.0,0.027495
...,...,...,...,...,...,...,...,...
4055,182138167,1.013844,1.032051,0.633561,0.521966,0.018207,-1.0,-0.018207
4056,51200,1.013844,1.032500,0.633561,0.519551,0.018656,-1.0,-0.018656
4057,50889,1.013844,1.033456,0.633561,0.518249,0.019612,-1.0,-0.019612
4060,4003822,1.013844,1.035326,0.633561,0.510996,0.021482,-1.0,-0.021482
4062,227194,1.013844,1.040946,0.633561,0.497052,0.027102,-1.0,-0.027102