# 220211

# Library

In [1]:
import numpy as np, os
import pandas as pd
import tensorflow as tf
from tqdm import tqdm

# 결과 확인을 용이하게 하기 위한 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# Data load

In [2]:
all_best = pd.read_csv('./dsml_data/df_all_best_for_meth1.csv') # only for preds, preds2, diff_preds...
# all_diff = pd.read_csv('./dsml_data/df_all_diff_for_meth1.csv')
# all_preds = pd.read_csv('./dsml_data/df_all_preds_for_meth1.csv')

# d1d5_best = pd.read_csv('./dsml_data/df_d1d5_best_for_meth1.csv')
# d1d5_diff = pd.read_csv('./dsml_data/df_d1d5_diff_for_meth1.csv')
# d1d5_preds = pd.read_csv('./dsml_data/df_d1d5_preds_for_meth1.csv')

# d6d10_best = pd.read_csv('./dsml_data/df_d6d10_best_for_meth1.csv')
# d6d10_diff = pd.read_csv('./dsml_data/df_d6d10_diff_for_meth1.csv')
# d6d10_preds = pd.read_csv('./dsml_data/df_d6d10_preds_for_meth1.csv')

In [3]:
all_best_for_ReLU = pd.read_csv('./dsml_data/df_all_best.csv')

In [4]:
all_best
# all_diff
# all_preds

# d1d5_best
# d1d5_diff
# d1d5_preds

# d6d10_best
# d6d10_diff
# d6d10_preds

,feature,baseline_bce,bce,preds_mean,preds2_mean,diff,diff_preds
0,904224461,1.013844,1.011739,0.633561,0.622529,-0.002106,-0.011032
1,69152068,1.013844,1.012304,0.633561,0.633442,-0.001540,-0.000120
2,536242558,1.013844,1.012476,0.633561,0.639803,-0.001368,0.006242
3,91464024,1.013844,1.012594,0.633561,0.640399,-0.001250,0.006838
4,37205036174,1.013844,1.012601,0.633561,0.639982,-0.001243,0.006421
...,...,...,...,...,...,...,...
4063,10019055302,1.013844,1.041340,0.633561,0.766674,0.027495,0.133112
4064,54817525,1.013844,1.042170,0.633561,0.767467,0.028326,0.133906
4065,67434504,1.013844,1.046685,0.633561,0.777882,0.032840,0.144320
4066,74606211,1.013844,1.050331,0.633561,0.784815,0.036486,0.151254
4067,409606211,1.013844,1.073784,0.633561,0.826544,0.059940,0.192982

# ~~preds 생성 당시 계산 실수, 부호 전환.~~ 
# 계산 잘 했었음.

In [5]:
#all_preds['diff_preds'] = -all_preds['diff_preds']
#all_preds
#all_preds = all_preds.sort_values('diff_preds', ascending = True)
#all_preds = all_preds.reset_index(drop = True)

In [6]:
#all_preds

In [7]:
#all_best['diff_preds'] = -all_best['diff_preds']
#all_best
#all_best = all_best.sort_values('diff_preds', ascending = True)
#all_best = all_best.reset_index(drop = True)

# ReLU

In [8]:
for i,j in enumerate(all_best_for_ReLU['diff']):
    if j <= 0:
        all_best_for_ReLU['diff'][i] = 0
all_best_for_ReLU

<ipython-input-8-86b9ebd9b2c1>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_best_for_ReLU['diff'][i] = 0

          feature  baseline_bce       bce      diff
0           51006      1.014362  1.001220  0.000000
1     63323026201      1.014362  1.006389  0.000000
2           51277      1.014362  1.006995  0.000000
3               0      1.014362  1.009931  0.000000
4     55390000401      1.014362  1.010688  0.000000
...           ...           ...       ...       ...
4063  10019055302      1.014362  1.041859  0.027498
4064     54817525      1.014362  1.043492  0.029130
4065     67434504      1.014362  1.046829  0.032467
4066     74606211      1.014362  1.051030  0.036668
4067    409606211      1.014362  1.073542  0.059180

[4068 rows x 4 columns]

In [9]:
# for i,j in enumerate(all_diff['diff']):
#     if j <= 0:
#         all_diff['diff'][i] = 0
# all_diff

# sign

In [10]:
# for i,j in enumerate(all_preds['diff_preds']):
#     if j>0:
#         all_preds['diff_preds'][i] = 1
# #    elif j==0:
# #        all_preds['diff_preds'][i] = 0
#     elif j<0:
#         all_preds['diff_preds'][i] = -1

In [11]:
# all_preds

In [12]:
for i,j in enumerate(all_best['diff_preds']):
    if j>0:
        all_best['diff_preds'][i] = 1
    elif j==0:
        all_best['diff_preds'][i] = 0
    elif j<0:
        all_best['diff_preds'][i] = -1

<ipython-input-12-62a8ef79243b>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_best['diff_preds'][i] = -1
<ipython-input-12-62a8ef79243b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_best['diff_preds'][i] = 1

# Method1
```
Method1 = all_best_for_ReLU['diff'] * all_best['diff_preds']
Method1 순서대로 (내림차순) sorting
```

In [32]:
# all_best['Method1'] = all_best['diff']*all_best['diff_preds']
# all_best
# all_best = all_best.sort_values("Method1", ascending= False)

ReLU_sort = all_best_for_ReLU.sort_values('feature').reset_index(drop = True)
ReLU_sort['diff']
Sign_sort = all_best.sort_values('feature').reset_index(drop = True)
Sign_sort['diff_preds']
# all_best_for_ReLU['diff'] * all_best['diff_preds']

0       0.000000
1       0.002118
2       0.003495
3       0.001575
4       0.005405
          ...
4063    0.002014
4064    0.000000
4065    0.013409
4066    0.000000
4067    0.000887
Name: diff, Length: 4068, dtype: float64

0      -1.0
1      -1.0
2       1.0
3      -1.0
4       1.0
       ...
4063   -1.0
4064   -1.0
4065    1.0
4066    1.0
4067    1.0
Name: diff_preds, Length: 4068, dtype: float64

In [33]:
Method1 = ReLU_sort.copy()

In [34]:
Method1.drop(['baseline_bce', 'bce'], axis = 1, inplace = True)

In [36]:
Method1['diff_preds'] = Sign_sort['diff_preds']

In [37]:
Method1['Method1'] = ReLU_sort['diff'] * Sign_sort['diff_preds']
Method1

          feature      diff  diff_preds   Method1
0               0  0.000000        -1.0 -0.000000
1           50803  0.002118        -1.0 -0.002118
2           50804  0.003495         1.0  0.003495
3           50805  0.001575        -1.0 -0.001575
4           50806  0.005405         1.0  0.005405
...           ...       ...         ...       ...
4063  78112001103  0.002014        -1.0 -0.002014
4064  79511050204  0.000000        -1.0 -0.000000
4065  87701071218  0.013409         1.0  0.013409
4066  87701083336  0.000000         1.0  0.000000
4067  87701089415  0.000887         1.0  0.000887

[4068 rows x 4 columns]

In [38]:
Method1 = Method1.sort_values('Method1', ascending = False)
Method1

          feature      diff  diff_preds   Method1
2195    409606211  0.059180         1.0  0.059180
1276     74606211  0.036668         1.0  0.036668
1081     67434504  0.032467         1.0  0.032467
982      54817525  0.029130         1.0  0.029130
2744  10019055302  0.027498         1.0  0.027498
...           ...       ...         ...       ...
162         51200  0.016966        -1.0 -0.016966
1815    182138167  0.017109        -1.0 -0.017109
37          50889  0.018246        -1.0 -0.018246
469       4003822  0.019987        -1.0 -0.019987
383        227194  0.025418        -1.0 -0.025418

[4068 rows x 4 columns]